# Patina Dark theme for Alacritty

[colors.primary]
background = "#121212"
foreground = "#dbd7ca"

[colors.cursor]
text = "#121212"
cursor = "#dbd7ca"

[colors.selection]
text = "#dbd7ca"
background = "#42403d"

[colors.normal]
black = "#2e2e2e"
red = "#cb7676"
green = "#4d9375"
yellow = "#e6cc77"
blue = "#6db3c2"
magenta = "#c98a7d"
cyan = "#5da9a7"
white = "#dbd7ca"

[colors.bright]
black = "#585858"
red = "#cb7676"
green = "#4d9375"
yellow = "#e6cc77"
blue = "#6db3c2"
magenta = "#c98a7d"
cyan = "#5da9a7"
white = "#dbd7ca"
